### ISSUE TITLE
bxv.gg/headless bot detection doesnt work lmao

### ISSUE THREAD

**Issue by SyntaxSparkk** [41Baloo/bxv.gg#1]
```py
import undetected_chromedriver as uc

if __name__ == '__main__':
    driver = uc.Chrome()
    driver.get('https://bxv.gg/headless')
   
    input()
```
( test it out yourself)

![image](https://user-images.githubusercontent.com/105955582/199348170-942041b9-79f8-413c-9652-3c6b2ea52006.png)

**Comment by SyntaxSparkk** [comment]
two of my friends went to the website on their real browser (not automated) and they didnt pass the check

**Comment by 41Baloo** [comment]
i assume undetected chromedriver is headful. The checks were mainly ment against headless browsers, hence the name. (https://bxv.gg/headless is also kinda a janky detection and does not even come close to the detection abilitys bxv.gg had) For your friends, did it say they „may“ have been blocked or that they „defnitely“ would have been blocked?

**Comment by SyntaxSparkk** [comment]
yeah i just realized it was for headless browsers only after i posted the issue lmao. 

here is the updated one (headless) 

good job 

![datadome_undetected_webddriver](https://user-images.githubusercontent.com/105955582/199349493-f1f36576-20f8-4d19-bbbe-37866027a24c.png)

**Comment by standfv** [comment]
aithedev scammer
![26EAEFDA-290B-45F4-806A-023342379D27](https://user-images.githubusercontent.com/27364465/215154170-d5b8f1f9-3460-47ca-8922-bcde8b6879a2.jpeg)

**Comment by standfv** [comment]
![A1B4DDF1-E4CE-4B51-9C4B-D7ED5326281E](https://user-images.githubusercontent.com/27364465/215154328-8632a894-87e8-4f33-88fc-8648634075e2.png)
